### ISSUE TITLE
The attachment link in your post is broken.

### ISSUE THREAD

**Issue by offense360** [jloh02/jloh02#1]
Good to see your CTF write up.
One of the links in the body https://blog.jloh02.dev/ctf/cddc-quals-2023/files/CTF/cddc-quals-2023/Confidential.docx is incorrect.

Here's the link: https://blog.jloh02.dev//files/CTF/cddc-quals-2023/Confidential.docx
You need to change the address.

**Comment by jloh02** [comment]
Thanks for pointing it out! Have updated it accordingly
